// Website pattern knowledge base — 8 categories with layout/design best practices
// Injected into new builds to guide the AI toward professional output

interface WebsitePattern {
  category: string
  keywords: string[]
  layout: string
  sections: string[]
  designTone: string
  colorApproach: string
  heroPattern: string
  mustHave: string[]
  avoid: string[]
  imageKeywords?: string
}

const PATTERNS: WebsitePattern[] = [
  {
    category: "saas_landing",
    keywords: ["saas", "software", "app", "platform", "tool", "dashboard", "analytics", "crm", "project management", "api", "startup", "product", "b2b"],
    layout: "Clean, minimal, high contrast. Lots of white space. Linear/Vercel/Stripe aesthetic.",
    sections: ["Navbar (logo + nav + CTA)", "Hero (headline + subhead + CTA + product screenshot)", "Social proof (logos or stats bar)", "Features (3-column icon grid)", "How it works (numbered steps)", "Pricing (3-tier cards)", "Testimonials", "Final CTA banner", "Footer"],
    designTone: "Professional, confident, modern tech. Trust-building.",
    colorApproach: "Dark navy or white base. Electric blue/violet accent. High contrast CTAs.",
    heroPattern: "Large bold headline (max 8 words), single-sentence subhead, two CTAs (primary + secondary), product screenshot or animation below",
    mustHave: ["Specific metric in hero (e.g., '10x faster', '47% reduction')", "Real company name (not 'YourBrand')", "Pricing with actual numbers", "Social proof — logos OR testimonials (not both)"],
    avoid: ["Stock photo heroes", "Vague headlines like 'Streamline your workflow'", "More than 3 nav items + CTA", "Gradients on everything"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?technology,office,modern | Team: https://source.unsplash.com/400x400/?professional,portrait,business | Feature: https://source.unsplash.com/800x600/?software,laptop,workspace",
  },
  {
    category: "ecommerce",
    keywords: ["shop", "store", "ecommerce", "buy", "product", "cart", "checkout", "sell", "merchandise", "clothing", "fashion", "sneakers", "jewelry"],
    layout: "Product-first. Large imagery. Sticky cart. Mobile-optimized grid.",
    sections: ["Navbar (logo + search + cart icon)", "Hero banner (seasonal promo)", "Featured categories (visual grid)", "Product grid (cards with image, name, price)", "Bestsellers carousel", "Brand story / USP", "Reviews", "Footer with trust badges"],
    designTone: "Aspirational, visual, brand-forward.",
    colorApproach: "Match product category. Fashion = minimal black/white. Outdoors = earthy greens. Tech = dark + neon.",
    heroPattern: "Full-width image with overlay text and shop CTA. Alternate: split layout (image left, text right).",
    mustHave: ["Working cart state (add/remove items)", "Product cards with real prices", "Filter/sort UI (even if not functional)", "Trust badges (free shipping, returns, secure)"],
    avoid: ["Text-only product cards", "Generic 'Shop Now' as the only CTA", "Hiding the cart"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?fashion,shopping,product | Product: https://source.unsplash.com/600x600/?clothing,product,lifestyle | Banner: https://source.unsplash.com/1600x600/?sale,shopping,retail",
  },
  {
    category: "restaurant_cafe",
    keywords: ["restaurant", "cafe", "coffee", "food", "menu", "dining", "bistro", "bar", "bakery", "pizza", "sushi", "brunch", "catering"],
    layout: "Atmosphere-first. Full-bleed hero. Warm, inviting. Menu prominently featured.",
    sections: ["Sticky nav (logo + Hours + Reserve CTA)", "Full-bleed hero (atmospheric photo + tagline)", "Menu highlights (cards with image + price)", "About / Story section", "Hours & Location", "Reservation CTA", "Reviews (Google/Yelp style)", "Footer"],
    designTone: "Warm, artisanal, inviting. 'Come in and stay a while' energy.",
    colorApproach: "Warm earth tones (amber, terracotta, cream). Dark backgrounds for upscale. Bright for casual.",
    heroPattern: "Full-width atmospheric image, semi-transparent overlay, restaurant name + tagline, two CTAs: 'View Menu' + 'Reserve a Table'",
    mustHave: ["Real menu items with prices (make them up)", "Hours and address", "Reservation or order CTA", "Brand name (not 'Our Restaurant')"],
    avoid: ["Stock photo food grid without context", "No menu/prices", "Corporate blue color palette", "Missing contact info"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?restaurant,dining,food | Menu items: https://source.unsplash.com/400x300/?[specific-dish],food | Team: https://source.unsplash.com/400x400/?chef,kitchen,cook | Gallery: https://source.unsplash.com/800x600/?restaurant,interior,ambiance",
  },
  {
    category: "portfolio_agency",
    keywords: ["portfolio", "agency", "designer", "developer", "freelance", "creative", "studio", "branding", "web design", "photography", "architect"],
    layout: "Work-first. Large case study images. Personal/team story. Clean and confident.",
    sections: ["Minimal nav (name + Work + About + Contact)", "Hero (name, role, 1-line tagline, scroll CTA)", "Selected work (case study cards)", "Services or skills", "About / Story", "Testimonials", "Contact CTA", "Footer"],
    designTone: "Confident, creative, editorial. The work speaks.",
    colorApproach: "Usually monochrome (black/white) with one bold accent. Or match personal brand.",
    heroPattern: "Name large, role below, short personal tagline, one primary CTA to see work. Often asymmetric layout.",
    mustHave: ["3-5 fake case study projects with titles + descriptions", "Clear role/specialty", "Contact method", "Specific skills or tools listed"],
    avoid: ["Centering everything", "Too many colors", "Generic taglines like 'Crafting digital experiences'", "Missing actual work samples"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?creative,design,studio | Portfolio: https://source.unsplash.com/800x600/?design,creative,project | About: https://source.unsplash.com/400x400/?designer,professional,portrait",
  },
  {
    category: "dashboard_app",
    keywords: ["dashboard", "admin", "analytics", "metrics", "reports", "monitor", "management", "system", "internal", "tracker", "crm"],
    layout: "Sidebar navigation + main content area. Data-dense but scannable.",
    sections: ["Sidebar (logo + nav items with icons)", "Top bar (search + notifications + user avatar)", "Stats row (4 KPI cards)", "Charts (line/bar graphs)", "Data table (with search/filter)", "Recent activity feed"],
    designTone: "Professional, efficient, information-dense.",
    colorApproach: "Dark sidebar + light content, or all-light. Blue/indigo accents for interactive elements.",
    heroPattern: "Not applicable — lead with stats and charts immediately on load.",
    mustHave: ["Sidebar with 5-8 nav items + icons", "4 KPI stat cards", "At least one chart (fake data ok)", "Responsive table"],
    avoid: ["Marketing-style hero", "Too much animation", "Missing sidebar", "Unusable at real data density"],
    imageKeywords: "Avatar: https://source.unsplash.com/40x40/?person,portrait,professional | Background: https://source.unsplash.com/1600x900/?technology,data,office",
  },
  {
    category: "blog_editorial",
    keywords: ["blog", "magazine", "editorial", "news", "articles", "newsletter", "publication", "media", "content", "writing"],
    layout: "Reading-optimized. Clear typography hierarchy. Content density.",
    sections: ["Minimal header (logo + categories + search)", "Featured article (hero card)", "Article grid (cards with image, category, title, excerpt, author)", "Category tabs", "Newsletter signup", "Footer"],
    designTone: "Editorial, trustworthy, readable.",
    colorApproach: "Clean white/off-white base. Accent on category tags. Strong typography is the design.",
    heroPattern: "Large featured article with image, category badge, title, excerpt and author. Grid of 3 secondary articles below.",
    mustHave: ["Readable font (serif for editorial feel)", "Category tags", "Article cards with author and date", "At least 6 fake articles"],
    avoid: ["Auto-play media", "Clutter/too many elements", "Poor line length (too wide)", "Missing reading time"],
    imageKeywords: "Featured: https://source.unsplash.com/1200x600/?article,editorial,writing | Thumbnail: https://source.unsplash.com/800x500/?[topic],blog | Author: https://source.unsplash.com/60x60/?person,portrait",
  },
  {
    category: "landing_service",
    keywords: ["service", "agency", "consulting", "law", "accounting", "plumbing", "electrician", "cleaning", "roofing", "contractor", "insurance", "mortgage", "real estate"],
    layout: "Trust-first. Local/professional. Clear services and contact.",
    sections: ["Nav (logo + Services + About + Contact + phone)", "Hero (service + location + trust signals)", "Services grid (3-6 cards)", "Why us (3 USP columns)", "Process steps", "Testimonials", "CTA banner ('Get a free quote')", "Contact form", "Footer"],
    designTone: "Trustworthy, local, professional. Customers need to feel safe choosing you.",
    colorApproach: "Industry-appropriate. Legal = navy/gold. Trades = bold red/blue. Medical = blue/green.",
    heroPattern: "Headline = what + who + where. Subhead = key benefit. CTA = 'Get Free Quote' or 'Schedule Service'. Trust signal = years in business, rating, or guarantee.",
    mustHave: ["Phone number visible in nav", "Clear list of services", "Free quote or contact CTA", "Customer reviews"],
    avoid: ["Burying contact info", "No local signals (city/area name)", "Weak CTAs like 'Learn More'"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?[service-type],professional,work | Team: https://source.unsplash.com/400x400/?worker,professional,portrait | Gallery: https://source.unsplash.com/800x600/?[service],job,results",
  },
  {
    category: "mobile_app_landing",
    keywords: ["mobile app", "ios", "android", "app store", "download", "phone app", "native app"],
    layout: "App-focused. Phone mockups. Download CTAs. Feature highlights.",
    sections: ["Nav (logo + Features + Pricing + Download)", "Hero (headline + phone mockup + download badges)", "Feature highlights (screenshot + text, alternating)", "Social proof (ratings, downloads)", "Pricing or plans", "Download CTA banner", "Footer"],
    designTone: "Modern, polished, mobile-first energy.",
    colorApproach: "Gradient backgrounds, vibrant accent. App Store aesthetic.",
    heroPattern: "Left: headline + subhead + App Store + Google Play badges. Right: phone mockup showing app UI.",
    mustHave: ["App Store + Google Play download buttons", "Phone mockup (CSS-only is fine)", "Feature screenshots", "App ratings/download count"],
    avoid: ["Desktop-only layout", "No download CTA", "Missing app store links"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?mobile,app,smartphone | Feature: https://source.unsplash.com/800x600/?phone,screen,technology | Lifestyle: https://source.unsplash.com/800x600/?person,phone,app",
  },
  {
    category: "luxury_spa_salon",
    keywords: ["spa", "salon", "beauty", "massage", "facial", "nails", "waxing", "blowout", "medspa", "skincare", "esthetics", "lashes", "brows", "wellness retreat"],
    layout: "Sensory-first. Full-bleed photography. Calm, uncluttered. Booking always one tap away.",
    sections: ["Navbar with sticky 'Book Now' CTA", "Cinematic hero (ambient photo + elegant tagline)", "StickyBar for promotions or new client offers", "Services menu with pricing", "Before/after results slider", "Meet the team (credentials + warmth)", "Client reviews with star ratings", "Booking widget (date, service, staff)", "Map + hours", "Footer"],
    designTone: "Luxurious, serene, aspirational. Clients should feel relaxed before they even walk in.",
    colorApproach: "Soft neutrals: champagne, blush, sage, warm white. Gold or muted rose as accent. Never bright primaries.",
    heroPattern: "Full-width atmospheric photo (spa interior or treatment in progress), minimal overlay text, single CTA: 'Book Your Experience'. No clutter.",
    mustHave: ["Booking form with service selector, date picker, and staff preference", "Before/after photo slider (skin, hair, nails — whatever fits)", "Real pricing on service cards — clients expect transparency", "New client special offer prominently displayed"],
    avoid: ["Bright or corporate colors", "Stock photo clichés (candles on rocks)", "Hiding prices", "Dense text blocks — this is a visual/emotional category"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?spa,wellness,luxury | Team: https://source.unsplash.com/400x400/?esthetician,professional,portrait | Before: https://source.unsplash.com/400x300/?skin,texture,close-up | After: https://source.unsplash.com/400x300/?glowing,skin,beauty | Gallery: https://source.unsplash.com/800x600/?spa,treatment,relaxation",
  },
  {
    category: "medical_dental",
    keywords: ["dentist", "dental", "doctor", "clinic", "medical", "orthodontist", "dermatologist", "chiropractor", "optometrist", "pediatrician", "urgent care", "healthcare", "physician", "surgeon"],
    layout: "Trust-first, clinical-clean. Patients need to feel safe and informed before booking.",
    sections: ["Navbar (logo + Services + About + Insurance + phone number)", "Hero (warm photo of staff + reassuring headline)", "Services grid with condition/treatment cards", "Trust badges (board certified, years of experience, insurance accepted)", "Doctor/team bios with credentials", "Before/after results (smile transformations, skin results)", "Patient reviews (Google star ratings)", "Online booking widget", "Map and office hours", "Footer"],
    designTone: "Reassuring, warm, and credible. Patients are often anxious — the site should calm and convert.",
    colorApproach: "Clean white or light gray base. Blue or teal accent for trust. Warm photography balances clinical coldness.",
    heroPattern: "Smiling doctor or welcoming waiting room photo, headline focused on patient outcome (e.g., 'Your Healthiest Smile Starts Here'), two CTAs: 'Book Appointment' + 'Meet Our Team'.",
    mustHave: ["Insurance logos or 'We accept most insurance' statement", "Doctor credentials (MD, DDS, board certifications) on team cards", "Online booking or prominent phone number", "Real patient testimonials with star ratings"],
    avoid: ["Sterile stock-photo operating rooms", "Burying the phone number", "Vague headlines like 'Quality Care for the Whole Family'", "No pricing or insurance info"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?doctor,clinic,healthcare | Team: https://source.unsplash.com/400x400/?doctor,medical,portrait | Office: https://source.unsplash.com/800x600/?clinic,medical,office | Before/After: https://source.unsplash.com/400x300/?smile,teeth,dental",
  },
  {
    category: "fitness_gym",
    keywords: ["gym", "fitness", "crossfit", "yoga", "pilates", "personal trainer", "bootcamp", "martial arts", "boxing", "cycling", "studio", "health club", "weightlifting", "strength"],
    layout: "High-energy. Bold imagery. Clear membership path. Community-forward.",
    sections: ["Navbar with 'Start Free Trial' CTA", "Hero (action shot + motivational headline)", "Social proof (member count, Google rating, transformation results)", "Class/program cards with schedule and difficulty", "How to get started (3-step process)", "Trainer bios with specialties", "Membership pricing tiers", "Member testimonials + transformation photos", "Contact and location", "Footer"],
    designTone: "Energetic, motivational, community-driven. Visitors should feel they can achieve their goals here.",
    colorApproach: "High contrast: black + electric yellow, dark navy + orange, or red + white. Bold, athletic. Avoid soft pastels.",
    heroPattern: "Full-bleed action photo or video loop. Bold motivational headline (5-7 words). Subhead about community or results. CTA: 'Start Free Trial' or 'Claim Your Free Class'.",
    mustHave: ["Free trial or intro offer CTA above the fold", "Clear membership pricing (monthly, annual, drop-in)", "Class schedule or program overview", "Transformation testimonials with photos if possible"],
    avoid: ["Soft or feminine pastels (unless niche yoga/pilates)", "Hiding pricing until contact", "Generic 'Get Fit' copy", "No social proof — skeptics need proof this gym gets results"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?gym,fitness,workout | Team: https://source.unsplash.com/400x400/?trainer,fitness,portrait | Classes: https://source.unsplash.com/800x600/?exercise,class,group | Transformation: https://source.unsplash.com/400x300/?fitness,strength,athlete",
  },
  {
    category: "legal_professional",
    keywords: ["law firm", "attorney", "lawyer", "legal", "counsel", "litigation", "injury", "divorce", "criminal defense", "immigration", "estate planning", "corporate law", "solicitor", "barrister"],
    layout: "Authority-first. Credibility signals everywhere. Clear practice areas. Easy consultation path.",
    sections: ["Navbar (logo + Practice Areas + About + Contact + phone)", "Hero (professional team photo + bold results-focused headline)", "Case stats (settlements won, years experience, cases handled)", "Practice area cards", "Attorney bios with bar admissions and credentials", "Case timeline or process walkthrough", "Client testimonials and case results", "Free consultation CTA", "Contact form", "Footer"],
    designTone: "Authoritative, composed, trustworthy. Clients are often scared — they need a firm that projects total competence.",
    colorApproach: "Navy blue, charcoal, or deep gray base. Gold or white accent. Conservative — no trendy gradients or bright colors.",
    heroPattern: "Professional team or courthouse photo, headline anchored in outcomes ('Aggressive Representation. Real Results.'), two CTAs: 'Free Consultation' + 'View Practice Areas'. Display a key stat (e.g., '$50M+ recovered') in the hero.",
    mustHave: ["Key stat in hero or just below (cases won, settlements, years experience)", "Practice area breakdown — clients need to confirm you handle their issue", "Attorney credentials with bar admissions and notable cases", "Free consultation CTA with form or phone — lower barrier to contact"],
    avoid: ["Casual or friendly tone — this is a high-stakes service", "Hiding attorney credentials", "Slow load time — clients shop multiple firms quickly", "Vague practice areas like 'We handle all legal matters'"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?law,courthouse,legal | Team: https://source.unsplash.com/400x400/?lawyer,attorney,professional | Office: https://source.unsplash.com/800x600/?law,office,professional",
  },
  // ── NEW PATTERNS (15 additional industries) ──────────────────────────────
  {
    category: "bakery_pastry",
    keywords: ["bakery", "pastry", "bread", "croissant", "cake", "cupcake", "patisserie", "boulangerie", "sourdough", "artisan bread", "custom cake", "wedding cake", "baked goods", "pastry shop"],
    layout: "Warm, cozy, artisan. Product photography drives desire. Seasonal menus feel handcrafted.",
    sections: ["Navbar (logo + Menu + Order + Hours + Contact)", "Hero (storefront or hero pastry photo + warm tagline)", "Banner (daily specials or seasonal highlight)", "MenuGrid (pastries, breads, cakes with photos + prices)", "Gallery (product and bakery interior photos)", "Custom Order CTA section", "HoursTable (baked fresh daily — hours matter)", "Reviews (Google/Yelp style)", "MapSection", "Footer"],
    designTone: "Warm, cozy, handcrafted. Customers should smell the bread through the screen.",
    colorApproach: "Warm creams, buttery yellows, terracotta, warm browns. Kraft paper aesthetic. Avoid cold blues or sterile whites.",
    heroPattern: "Storefront or beauty shot of signature item, overlaid with bakery name + tagline ('Baked Fresh Every Morning'), CTA: 'Order for Pickup'. Seasonal badge optional.",
    mustHave: ["Menu with real item names and prices (croissants, sourdough, tarts, etc.)", "Pickup order CTA or online ordering link", "Seasonal specials callout (e.g., fall pumpkin bread, holiday cookies)", "Custom order form or inquiry link for cakes and events"],
    avoid: ["Generic food stock photos", "Cold color palettes", "Missing hours (bakeries have early/specific hours)", "No prices on menu items"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?bakery,pastry,bread | Menu: https://source.unsplash.com/400x300/?croissant,cake,pastry | Gallery: https://source.unsplash.com/800x600/?bakery,interior,bread | Product: https://source.unsplash.com/600x600/?cake,pastry,baked",
  },
  {
    category: "coffee_shop",
    keywords: ["coffee shop", "coffeehouse", "espresso bar", "latte", "cappuccino", "cold brew", "pour over", "barista", "third wave coffee", "specialty coffee", "coffee roaster"],
    layout: "Modern cozy. Beverage photography front-and-center. Community and workspace vibes.",
    sections: ["Navbar (logo + Menu + About + Hours + Find Us)", "Hero (signature drink or cozy interior photo + tagline)", "Banner (seasonal drink spotlight or loyalty program)", "MenuGrid (drinks + food items with photos + prices)", "Gallery (cafe interior, latte art, food)", "HoursTable", "MapSection", "Reviews", "Footer"],
    designTone: "Modern, cozy, community-first. A mix of craft coffee culture and welcoming third place.",
    colorApproach: "Warm off-whites, deep espresso browns, sage green, or muted terracotta. One bold accent for CTAs. Never sterile white.",
    heroPattern: "Close-up latte art or cafe interior, bold name + one-line tagline, two CTAs: 'View Menu' + 'Find Us'. Optional loyalty program teaser.",
    mustHave: ["Drink menu with real names and prices (lattes, cold brew, seasonal specials)", "Loyalty program callout (stamp card, app, or points)", "WiFi/workspace mention if applicable", "Seasonal drink feature (pumpkin spice, lavender, holiday specials)"],
    avoid: ["Generic coffee stock photos", "Hiding the address/hours", "No prices on menu", "Missing community/vibe messaging"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?coffee,cafe,espresso | Menu: https://source.unsplash.com/400x300/?latte,coffee,drink | Gallery: https://source.unsplash.com/800x600/?cafe,interior,cozy | Seasonal: https://source.unsplash.com/600x400/?coffee,seasonal,drink",
  },
  {
    category: "bar_nightclub",
    keywords: ["bar", "nightclub", "club", "lounge", "cocktail bar", "sports bar", "dive bar", "rooftop bar", "bottle service", "nightlife", "pub", "tavern", "happy hour", "craft cocktails", "mixology"],
    layout: "Bold, dark, atmospheric. Events and specials drive visits. Age-gated feel.",
    sections: ["Navbar (logo + Menu + Events + Reservations + Hours)", "Hero (moody venue or cocktail photo + bold name)", "Banner (weekly events, happy hour, or bottle service special)", "MenuGrid (signature cocktails + food if applicable)", "EventsList (upcoming nights, themed events, DJs)", "Gallery (venue ambiance, cocktails, crowd)", "Reviews", "HoursTable (late hours, age 21+ note)", "MapSection", "Footer"],
    designTone: "Bold, dark, exclusive. Guests should feel the energy before they arrive.",
    colorApproach: "Deep blacks, dark charcoals, and rich jewel tones (burgundy, navy, emerald). Neon or gold accents. High contrast.",
    heroPattern: "Full-bleed moody venue or hero cocktail photo, dark overlay, venue name large, tagline evoking experience, CTA: 'Reserve a Table' or 'Book Bottle Service'.",
    mustHave: ["Events calendar or upcoming nights list", "Bottle service / VIP booking CTA", "Happy hour callout with times and deals", "Age gate hint (21+ wording in footer or hero)"],
    avoid: ["Bright cheerful color palettes", "Daytime stock photos", "Missing hours (critical for night venues)", "No events or specials listed"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?bar,nightclub,cocktail | Cocktails: https://source.unsplash.com/400x300/?cocktail,drink,bar | Venue: https://source.unsplash.com/800x600/?nightclub,lounge,dark | Events: https://source.unsplash.com/800x600/?party,nightlife,crowd",
  },
  {
    category: "real_estate_agency",
    keywords: ["real estate agency", "realtor", "realty", "homes for sale", "buy a home", "sell a home", "home valuation", "mls listing", "real estate agent", "real estate broker", "property management", "housing market"],
    layout: "Professional, elegant. Property search drives conversion. Trust and local expertise first.",
    sections: ["Navbar (logo + Buy + Sell + Rent + About + Contact)", "Hero (luxury home photo + search CTA + tagline)", "Stats bar (homes sold, years experience, average sale price)", "ServiceCards (Buy / Sell / Rent / Invest)", "Featured Listings (property cards with photo, beds, baths, price)", "Team (agent profiles with credentials)", "Testimonials", "Contact / Free Home Valuation CTA", "MapSection", "Footer"],
    designTone: "Professional, elegant, trustworthy. Clients are making the biggest purchase of their lives.",
    colorApproach: "Navy, charcoal, or deep forest green base. Gold or white accent. Clean and aspirational.",
    heroPattern: "Luxury or aspirational home exterior photo, bold headline ('Your Dream Home Starts Here'), property search bar or CTA, key stat overlay (e.g., '#1 in [City] for 5 years').",
    mustHave: ["Property search CTA (link to MLS or search page)", "Free home valuation offer prominently displayed", "Stats: homes sold, years of experience, client satisfaction", "Market report download or neighborhood guides"],
    avoid: ["Generic headshots without credentials", "Missing property listings or examples", "Hiding agent contact info", "Vague value props without local market data"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?house,real-estate,home | Listings: https://source.unsplash.com/800x600/?house,property,exterior | Team: https://source.unsplash.com/400x400/?realtor,professional,portrait | Interior: https://source.unsplash.com/800x600/?home,interior,luxury",
  },
  {
    category: "auto_repair",
    keywords: ["auto repair", "car repair", "mechanic", "auto shop", "oil change", "brake repair", "tire shop", "transmission repair", "auto service", "car service", "automotive shop", "collision repair", "car diagnostics", "tune up"],
    layout: "Bold, trustworthy, efficient. Services and trust signals front-and-center. Easy booking.",
    sections: ["Navbar (logo + Services + About + Reviews + phone number)", "Hero (shop or mechanic photo + headline + trust signal)", "ServiceCards (oil change, brakes, AC, diagnostics, tires, alignment)", "TrustBadges (ASE certified, warranty, family-owned, BBB rated)", "StepProcess (Drop Off → Diagnose → Fix → Pickup)", "Reviews (Google star ratings)", "HoursTable", "MapSection", "Contact / Booking CTA", "Footer"],
    designTone: "Bold, honest, trustworthy. Customers need to feel confident before handing over their keys.",
    colorApproach: "Bold navy, red, or dark charcoal base. High-contrast white text. Orange or yellow accent for CTAs. Industrial feel.",
    heroPattern: "Clean shop or mechanic-at-work photo, headline built on trust ('Honest Repairs. Fair Prices.'), trust badge row below, CTAs: 'Book Service' + 'Get Free Estimate'.",
    mustHave: ["Online booking or appointment request form", "Free estimate CTA", "Service list with pricing (even ranges)", "ASE certification or warranty mention"],
    avoid: ["Soft or feminine color palettes", "Missing phone number in header", "No service descriptions or pricing", "No trust signals — customers fear getting ripped off"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?mechanic,auto-repair,garage | Services: https://source.unsplash.com/400x300/?car,repair,mechanic | Shop: https://source.unsplash.com/800x600/?garage,auto,workshop | Team: https://source.unsplash.com/400x400/?mechanic,portrait,professional",
  },
  {
    category: "photography_studio",
    keywords: ["photography studio", "photographer", "photo studio", "portrait photography", "wedding photographer", "commercial photography", "headshots", "photo session", "photoshoot", "boudoir photography", "newborn photography", "event photography"],
    layout: "Minimal, artistic, portfolio-first. Let the photos do the work. Clean and spacious.",
    sections: ["Minimal navbar (logo + Portfolio + About + Pricing + Contact)", "Hero (stunning portfolio shot + name + specialty)", "Portfolio galleries (by category: wedding, portrait, commercial, family)", "Team / Photographer bio", "PricingTable (session packages with what's included)", "Reviews", "Contact / Booking calendar CTA", "Footer"],
    designTone: "Minimal, artistic, confident. The portfolio is the product — keep the UI invisible.",
    colorApproach: "Near-monochrome: white, off-white, and charcoal. One subtle accent. Never compete with the photos.",
    heroPattern: "Full-bleed stunning portfolio image, minimal overlay: photographer name + specialty (e.g., 'Wedding & Portrait Photography'), one CTA: 'View My Work' or 'Book a Session'.",
    mustHave: ["Portfolio organized by shoot type (at least 3 categories)", "Online gallery proofing or delivery mention", "Pricing packages with clear inclusions", "Booking calendar or inquiry form"],
    avoid: ["Clashing colors that compete with photos", "Dense text paragraphs", "Hiding pricing (clients comparison-shop)", "Generic placeholder photos"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?photography,portrait,wedding | Portfolio: https://source.unsplash.com/800x600/?photography,portrait,professional | About: https://source.unsplash.com/400x400/?photographer,camera,portrait | Wedding: https://source.unsplash.com/800x600/?wedding,ceremony,couple",
  },
  {
    category: "wedding_venue",
    keywords: ["wedding venue", "event venue", "wedding hall", "banquet hall", "wedding space", "ceremony venue", "reception venue", "garden wedding", "barn wedding", "vineyard wedding", "wedding location", "wedding site"],
    layout: "Luxury, romantic, immersive. Gallery-first. Every photo should inspire a booking.",
    sections: ["Navbar (logo + Gallery + Packages + Availability + Contact)", "Hero (stunning ceremony or reception photo + tagline)", "Gallery (ceremony spaces, reception hall, outdoor areas)", "Stats (weddings hosted, max capacity, acres of grounds)", "Features (in-house catering, parking, day-of coordinator, bridal suite)", "PricingTable (packages: intimate, classic, grand)", "Reviews (couples testimonials)", "Availability / Booking CTA", "MapSection", "Contact", "Footer"],
    designTone: "Luxury, romantic, aspirational. Couples should feel their perfect day unfolding.",
    colorApproach: "Soft ivory, champagne, blush, sage. Gold accents. Never stark white or corporate blue.",
    heroPattern: "Full-bleed reception or ceremony photo, venue name in elegant serif font, tagline ('Where Love Stories Begin'), CTA: 'Check Availability' + 'Schedule a Tour'.",
    mustHave: ["Availability checker or date inquiry form", "Virtual tour link or gallery CTA", "Preferred vendor list mention", "Capacity and catering details in packages"],
    avoid: ["Missing pricing (major objection for couples budgeting)", "Dark or somber photography", "Generic stock wedding photos", "No capacity or guest count info"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?wedding,venue,ceremony | Gallery: https://source.unsplash.com/800x600/?wedding,reception,elegant | Outdoor: https://source.unsplash.com/800x600/?garden,wedding,outdoor | Couple: https://source.unsplash.com/800x600/?wedding,couple,romantic",
  },
  {
    category: "cleaning_service",
    keywords: ["cleaning service", "house cleaning", "maid service", "commercial cleaning", "office cleaning", "deep clean", "move out cleaning", "move in cleaning", "janitorial service", "cleaning company", "residential cleaning", "carpet cleaning", "window cleaning"],
    layout: "Fresh, professional, trust-first. Instant quoting drives conversion. Simple and clean.",
    sections: ["Navbar (logo + Services + About + Reviews + Book Now)", "Hero (clean, bright home photo + headline)", "ServiceCards (residential, commercial, deep clean, move-in/out, recurring)", "TrustBadges (bonded, insured, background-checked, satisfaction guaranteed)", "StepProcess (Book Online → We Arrive → We Clean → You Inspect)", "PricingTable (basic, standard, deep clean)", "Reviews (before/after results, star ratings)", "Contact / Instant Quote CTA", "Footer"],
    designTone: "Fresh, clean, professional. Customers are inviting strangers into their home — trust is everything.",
    colorApproach: "Clean whites, sky blues, and fresh greens. Bright, airy feel. Avoid dark or cluttered aesthetics.",
    heroPattern: "Bright, clean home interior or happy customer photo, headline ('Professional Cleaning You Can Trust'), trust badge row, CTAs: 'Get Instant Quote' + 'Book Today'.",
    mustHave: ["Instant online quote tool or pricing estimator", "Trust badges (bonded, insured, background-checked) above the fold", "Recurring service discount callout", "Satisfaction guarantee or re-clean policy"],
    avoid: ["Dark or dingy aesthetics", "Missing trust signals", "Hiding pricing or making quotes phone-only", "No service area mention"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?clean,home,interior | Services: https://source.unsplash.com/400x300/?cleaning,home,kitchen | Team: https://source.unsplash.com/400x400/?cleaner,professional,uniform | Results: https://source.unsplash.com/800x600/?clean,bright,spotless",
  },
  {
    category: "law_firm_general",
    keywords: ["law firm general", "legal services", "personal injury lawyer", "criminal defense attorney", "family law attorney", "divorce attorney", "immigration lawyer", "estate attorney", "business lawyer", "workers compensation", "wrongful death attorney"],
    layout: "Authority-first. Credibility at every scroll. Clear practice areas. Low-friction consultation path.",
    sections: ["Navbar (logo + Practice Areas + Our Attorneys + About + Contact + phone)", "Hero (professional team or courthouse photo + results headline)", "Stats (years of experience, cases won, clients served, settlements recovered)", "ServiceCards (practice areas: personal injury, family, criminal, business, estate)", "Team (attorney profiles with credentials, bar admissions)", "Timeline (how your case works: consultation → investigation → strategy → resolution)", "SocialProof (bar associations, awards, super lawyers badges)", "Reviews (client outcomes)", "Free Consultation CTA", "Contact form", "Footer"],
    designTone: "Authoritative, composed, results-driven. Clients are in crisis — project total competence.",
    colorApproach: "Deep navy, charcoal, or dark forest. Gold or white accents. Classic serif fonts signal authority.",
    heroPattern: "Professional team or legal office photo, bold outcome-focused headline ('We Fight. You Win.'), key stat displayed prominently (e.g., '$50M+ Recovered'), CTAs: 'Free Consultation' + 'View Practice Areas'.",
    mustHave: ["Key results stat (settlements, cases won) in hero", "Clear practice area cards — clients must self-identify", "Attorney credentials with bar admissions and recognitions", "Free consultation CTA with minimal friction (phone or quick form)"],
    avoid: ["Friendly casual tone — this is high-stakes", "Vague practice area descriptions", "Missing attorney photos and credentials", "Slow or cluttered layout — clients shop multiple firms quickly"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?law,justice,office | Team: https://source.unsplash.com/400x400/?lawyer,attorney,professional | Office: https://source.unsplash.com/800x600/?law,office,professional | Court: https://source.unsplash.com/800x600/?courthouse,justice,legal",
  },
  {
    category: "dental_office",
    keywords: ["dentist office", "dental practice", "teeth whitening", "dental implants", "invisalign provider", "orthodontist office", "family dentist", "cosmetic dentistry", "pediatric dentist", "dental care", "dental cleaning", "tooth extraction", "dental crown"],
    layout: "Clean, clinical + warm. Trust and comfort signals balanced. Booking must be effortless.",
    sections: ["Navbar (logo + Services + About + Insurance + New Patients + Book Now)", "Hero (warm smiling staff or patient photo + reassuring headline)", "ServiceCards (cleanings, fillings, whitening, implants, Invisalign, emergency)", "TrustBadges (ADA member, insurance accepted, new patients welcome, sedation available)", "Team (dentist + hygienists with credentials and warm bios)", "BeforeAfter (smile transformation slider)", "Reviews (Google star ratings)", "Booking widget (date/time picker)", "MapSection", "Footer"],
    designTone: "Clean, clinical, yet warm and welcoming. Patients are often anxious — the design should feel calm.",
    colorApproach: "Clean white base, teal or sky blue accents. Warm photography offsets clinical feel. Avoid overly sterile gray.",
    heroPattern: "Smiling dentist or happy patient photo, headline on patient outcome ('Your Best Smile Starts Here'), CTAs: 'Book Appointment' + 'New Patient Special', insurance note below.",
    mustHave: ["New patient special offer (first exam, x-rays, cleaning deal)", "Insurance accepted list or 'most insurance accepted'", "Online booking widget or prominent click-to-call", "Before/after smile gallery"],
    avoid: ["Sterile clinical stock photos only", "Hiding pricing or insurance info", "Missing new patient info", "No emergency contact for urgent care"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?dentist,smile,dental | Team: https://source.unsplash.com/400x400/?dentist,doctor,portrait | Office: https://source.unsplash.com/800x600/?dental,clinic,office | Smile: https://source.unsplash.com/400x300/?smile,teeth,beautiful",
  },
  {
    category: "pet_grooming",
    keywords: ["pet grooming", "dog grooming", "cat grooming", "dog wash", "pet salon", "dog groomer", "nail trim", "dog bath", "pet stylist", "mobile grooming", "pet spa", "dog haircut", "flea treatment"],
    layout: "Playful, friendly, pet-photo-forward. Booking and breed-specific info are key conversion drivers.",
    sections: ["Navbar (logo + Services + Gallery + Pricing + Book Now)", "Hero (adorable groomed dog/cat photo + playful tagline)", "ServiceCards (bath + brush, full groom, nail trim, teeth brushing, de-shed, spa add-ons)", "Gallery (before/after pet photos)", "Team (groomer bios with pet-love personality)", "PricingTable (by dog size or breed category)", "Reviews", "Booking widget", "MapSection", "Footer"],
    designTone: "Playful, warm, pet-obsessed. Pet parents want to trust you with their fur babies.",
    colorApproach: "Bright, friendly colors: sky blue, sunny yellow, grass green, or soft purple. Playful but not childish.",
    heroPattern: "Adorable freshly groomed dog photo, playful headline ('Your Pup Deserves the Best'), CTA: 'Book a Grooming' + breed/size selector.",
    mustHave: ["Breed-specific or size-based pricing table", "Before/after pet photo gallery", "Online booking or appointment request", "Loyalty program mention (punch card, free nail trim after X visits)"],
    avoid: ["Dull or corporate design — this is a fun, emotional category", "Missing pricing (pet parents comparison-shop)", "No pet photos", "Generic descriptions without breed/size specifics"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?dog,grooming,cute | Gallery: https://source.unsplash.com/800x600/?dog,puppy,cute | Services: https://source.unsplash.com/400x300/?dog,bath,grooming | Team: https://source.unsplash.com/400x400/?groomer,dog,portrait",
  },
  {
    category: "personal_trainer_coach",
    keywords: ["personal trainer", "life coach", "fitness coach", "online coach", "nutrition coach", "health coach", "transformation coach", "business coach", "mindset coach", "executive coach", "wellness coach", "1 on 1 training", "online personal training", "coaching program"],
    layout: "Energetic, inspiring, personal-brand-forward. Transformation proof drives conversions.",
    sections: ["Navbar (logo + Programs + Results + About + Book Free Call)", "Hero (action shot or confident portrait + bold motivational headline)", "Stats (clients transformed, goals achieved, years experience, rating)", "Features (1-on-1 training, custom nutrition, accountability coaching, online access)", "BeforeAfter (transformation photos or success stories)", "PricingTable (starter, pro, VIP packages)", "Testimonials (detailed success stories)", "Booking / Free Strategy Call CTA", "Contact", "Footer"],
    designTone: "Energetic, inspiring, authentic. Prospective clients need to believe in you AND themselves.",
    colorApproach: "Bold and motivational: black + gold, navy + orange, or deep purple + white. Avoid soft pastels unless niche wellness.",
    heroPattern: "Action shot or strong portrait photo, bold motivational headline ('Transform Your Body. Transform Your Life.'), key stat or social proof below, CTAs: 'Apply for Coaching' + 'Book Free Strategy Call'.",
    mustHave: ["Free strategy call or consultation CTA (lowers barrier)", "Transformation results / before-after proof", "Program quiz or application form", "Clear pricing with what's included in each tier"],
    avoid: ["Overly generic 'get fit' copy", "Missing transformation proof", "No way to book a discovery call", "Hiding pricing entirely"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?trainer,fitness,coaching | Results: https://source.unsplash.com/400x300/?fitness,transformation,strength | About: https://source.unsplash.com/400x400/?trainer,portrait,fit | Action: https://source.unsplash.com/800x600/?workout,training,exercise",
  },
  {
    category: "accounting_tax_firm",
    keywords: ["accounting firm", "accountant", "cpa firm", "tax preparation", "tax filing", "bookkeeping service", "payroll service", "enrolled agent", "irs representation", "financial statements", "small business accounting", "tax planning", "tax advisor", "tax professional"],
    layout: "Professional, trustworthy, organized. Process clarity and credentials reduce anxiety.",
    sections: ["Navbar (logo + Services + About + Resources + Contact + phone)", "Hero (professional team photo + trusted headline)", "ServiceCards (tax prep, bookkeeping, payroll, business consulting, IRS representation, financial planning)", "TrustBadges (CPA certified, enrolled agent, QuickBooks ProAdvisor, IRS authorized)", "Team (CPA bios with credentials)", "StepProcess (consultation → document collection → filing → review + planning)", "FAQ (common tax questions)", "Contact / Free Consultation CTA", "Footer"],
    designTone: "Professional, trustworthy, organized. Clients are handing over their finances — confidence is everything.",
    colorApproach: "Deep navy or forest green base. Gold or white accent. Conservative, trustworthy palette. Avoid trendy or playful designs.",
    heroPattern: "Professional office or team photo, headline about trust and expertise ('Accurate Books. Maximum Refunds.'), CTAs: 'Get Free Consultation' + 'Upload Documents', CPA badge visible.",
    mustHave: ["Secure document portal mention or link", "Tax calendar or deadline reminders section", "Free first consultation CTA", "CPA/EA credentials prominent on team cards"],
    avoid: ["Hiding credentials", "Casual tone — money is serious", "Missing deadline-awareness content (tax season urgency)", "No secure document handling mention"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?accounting,finance,office | Team: https://source.unsplash.com/400x400/?accountant,professional,portrait | Office: https://source.unsplash.com/800x600/?office,finance,professional | Documents: https://source.unsplash.com/400x300/?documents,tax,finance",
  },
  {
    category: "nonprofit_charity",
    keywords: ["nonprofit", "charity", "foundation", "ngo", "501c3", "donate", "volunteer", "fundraiser", "mission driven", "impact", "community organization", "humanitarian", "social good", "giving back", "beneficiaries", "cause"],
    layout: "Warm, mission-driven, impact-forward. Emotional connection drives donations and volunteering.",
    sections: ["Navbar (logo + Mission + Programs + Stories + Get Involved + Donate)", "Hero (impact photo + mission statement)", "Stats (people helped, volunteers, years active, dollars raised)", "Features / Programs (what you do, who you serve)", "Timeline (organization history and milestones)", "Testimonials (beneficiary stories, real impact)", "CTA section (Donate + Volunteer)", "Partners / Funders (donor org logos)", "Newsletter signup", "Contact", "Footer"],
    designTone: "Warm, hopeful, mission-driven. Donors and volunteers need to feel the impact before they act.",
    colorApproach: "Warm, human colors: deep teal, warm orange, golden yellow, or earthy green. Avoid corporate cold blues. Photos drive emotion.",
    heroPattern: "Powerful impact photo (people served or community), bold mission statement headline, two CTAs: 'Donate Now' + 'Volunteer Today'. Key stat (e.g., '10,000 families served') below hero.",
    mustHave: ["Donation form or Donate button prominently displayed", "Volunteer signup form or CTA", "Impact report download or stats section", "Beneficiary stories or testimonials"],
    avoid: ["Corporate or cold design", "Burying the donation CTA", "Vague mission statements without proof", "Missing impact numbers"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?charity,volunteer,community | Impact: https://source.unsplash.com/800x600/?help,community,people | Stories: https://source.unsplash.com/400x300/?smile,community,volunteer | Programs: https://source.unsplash.com/800x600/?nonprofit,education,charity",
  },
  {
    category: "ecommerce_online_store",
    keywords: ["online store", "web store", "shopify store", "woocommerce", "product store", "digital store", "dropshipping store", "retail online", "buy online", "ecommerce site", "sell products online", "online boutique", "online marketplace"],
    layout: "Conversion-optimized. Product imagery dominant. Friction-free path to checkout.",
    sections: ["Navbar (logo + Shop + Categories + Search + Cart icon)", "Banner (sale, promo code, or free shipping offer)", "Hero (brand story or hero product)", "ShopGrid (featured products with image, name, price, add-to-cart)", "Features (free shipping threshold, easy returns, secure checkout, customer support)", "SocialProof (customer photos using the product + reviews)", "Reviews (star ratings with quotes)", "Newsletter signup (discount incentive)", "Footer (trust badges, links, payment icons)"],
    designTone: "Modern, conversion-focused, brand-forward. Every element should nudge toward purchase.",
    colorApproach: "Match the brand/product category. Fashion = minimal black/white. Wellness = earth tones. Tech = dark + neon. Always high-contrast CTAs.",
    heroPattern: "Brand lifestyle photo or product hero, value prop headline, primary CTA: 'Shop Now' or 'Explore Collection'. Optional: countdown timer for sale.",
    mustHave: ["Cart functionality (add/remove items, cart count in nav)", "Product cards with real prices and add-to-cart button", "Cart abandonment nudge (e.g., 'Only 3 left!' or email capture)", "Loyalty program or rewards mention"],
    avoid: ["Text-only product listings", "Hiding shipping costs until checkout", "No trust badges at checkout", "Missing product search or filtering"],
    imageKeywords: "Hero: https://source.unsplash.com/1600x900/?product,lifestyle,shopping | Products: https://source.unsplash.com/600x600/?product,item,flatlay | Social: https://source.unsplash.com/400x400/?customer,lifestyle,product | Banner: https://source.unsplash.com/1600x400/?sale,shopping,promo",
  },
]

export function matchPattern(prompt: string): WebsitePattern {
  const lower = prompt.toLowerCase()
  let bestMatch = PATTERNS[0]
  let bestScore = 0

  for (const p of PATTERNS) {
    const score = p.keywords.reduce((s, kw) => s + (lower.includes(kw) ? 1 : 0), 0)
    if (score > bestScore) { bestScore = score; bestMatch = p }
  }

  return bestMatch
}

export function buildWebsiteKnowledge(prompt: string): string {
  const p = matchPattern(prompt)
  const imgHint = p.imageKeywords ? ` | Images: ${p.imageKeywords}` : ""
  return `## Site guidance (${p.category}): ${p.designTone} | Colors: ${p.colorApproach} | Must: ${p.mustHave.slice(0,2).join(", ")} | Avoid: ${p.avoid.slice(0,2).join(", ")}${imgHint}`
}
