import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export async function POST(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth();
  if (!session?.user) return new Response("Unauthorized", { status: 401 });

  const { id } = await params;
  const { token, repoName, isPrivate = false } = await req.json();

  if (!token || !repoName) return Response.json({ error: "token and repoName required" }, { status: 400 });

  const project = await prisma.project.findFirst({
    where: { id, ownerId: session.user.id },
    include: { versions: { orderBy: { createdAt: "desc" }, take: 1 } },
  });
  if (!project?.versions[0]) return Response.json({ error: "No version to export" }, { status: 404 });

  const files: Record<string, string> = JSON.parse(project.versions[0].files);
  const headers = { Authorization: `token ${token}`, "Content-Type": "application/json", "User-Agent": "ThatCode" };

  // Get GitHub username
  const userRes = await fetch("https://api.github.com/user", { headers });
  if (!userRes.ok) return Response.json({ error: "Invalid GitHub token" }, { status: 401 });
  const ghUser = await userRes.json();

  // Create repo
  const createRes = await fetch("https://api.github.com/user/repos", {
    method: "POST",
    headers,
    body: JSON.stringify({ name: repoName, private: isPrivate, description: `Generated by ThatCode — ${project.name}`, auto_init: false }),
  });
  if (!createRes.ok) {
    const err = await createRes.json();
    return Response.json({ error: err.message ?? "Failed to create repo" }, { status: 400 });
  }
  const repo = await createRes.json();

  // Push each file
  const results = await Promise.allSettled(
    Object.entries(files).map(([path, content]) =>
      fetch(`https://api.github.com/repos/${ghUser.login}/${repoName}/contents/${path}`, {
        method: "PUT",
        headers,
        body: JSON.stringify({ message: `Add ${path}`, content: Buffer.from(content).toString("base64") }),
      })
    )
  );

  const failed = results.filter(r => r.status === "rejected").length;

  return Response.json({ repoUrl: repo.html_url, filesUploaded: results.length - failed, failed });
}
